### ISSUE TITLE
Missing hotdog.zip

### ISSUE THREAD

**Issue by zodiacon** [jeffprosise/ML.NET#1]

**Comment by jeffprosise** [comment]
Ah yes! Run the MLN-ImageClassification project to generate the zip file. Then copy the zip file into the Model folder of the MLN-NotHotDog project. The zip file is large, so I didn't want to make it part of the repo. Let me know if you have any questions!

**Comment by zodiacon** [comment]
Yes, that works. The ImageClassification project needs an update for the TensorFlow library to run properly.
I would suggest upgrading everything to VS 2019 and .NET Core. ML.NET with .NET Core can be compiled with AnyCPU rather than x64/x86.
Thanks
